"""add password_hash column for User Model

Revision ID: 37363e9efb35
Revises: 3574481cc6ce
Create Date: 2017-10-18 23:39:48.217337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37363e9efb35'
down_revision = '3574481cc6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
